ergo/data/covid19.py

See https://github.com/CSSEGISandData/COVID-19/issues/1250

Update HopkinsData url

---

ergo/__init__.py
ergo/data/covid19.py
ergo/metaculus.py
poetry.lock
pyproject.toml
tests/test_ergo.py

- Fix #11 
- Fix #12 
- Point to correct Johns Hopkins csv
...and test all of these things (some via unit tests, others via integration tests)

Fix minor issues

---

README.md
ergo/__init__.py
ergo/metaculus.py
poetry.lock
pyproject.toml
tests/test_ergo.py

Add and test functionality for dashboard, getting:
1. prediction results and
2. Metaculus questions
as dataframes

Dashboardv2

---

ergo/__init__.py
ergo/ppl.py
pyproject.toml

See colab https://colab.research.google.com/drive/1b9TYZvr-FVsW7yjkfHeNqZwrDFVoZ_qf

Add basic variational inference

---

ergo/metaculus.py
tests/test_ergo.py

and some minor refactoring
PR currently made to `dashboardv3` to show the correct diff; should be remade to master and that one should be the one merged

Add + test ability to make predictions on binary questions

---

.gitignore
.travis.yml
Makefile
README.md
docs/Makefile
docs/inference.rst
ergo/__init__.py
ergo/data/covid19.py
ergo/foretold.py
ergo/logistic.py
ergo/metaculus.py
ergo/ppl.py
poetry.lock
pyproject.toml
setup.cfg
tests/test_foretold.py
tests/test_jax.py
tests/test_logistic.py
tests/test_metaculus.py

Also:
- Support building docs locally
- Sort imports using isort

Use Makefiles

---

ergo/metaculus.py
notebooks/community_distributions.ipynb
tests/test_metaculus.py

Provides functionality to interact with Metaculus date questions 
Closes #72

Submit dates

---

docs/index.rst
docs/tips_google_sheets.rst

Add documentation for loading data from google sheets

Add documentation for loading data from google sheets

---

ergo/metaculus.py

Refactored Plotting Code

---

notebooks/el-paso/el-paso-no-output.ipynb

This allows us to get a fairly nice diff between this notebook and future versions, as seen in https://github.com/oughtinc/ergo/pull/207

Check in version of current el-paso notebok but cleared of output

---

tests/mocks.py
tests/test_metaculus.py

Added test for default names

---

ergo/metaculus.py

Get wrapped titles back now that the question.name object is automatically set to be the title

updated plots to reflect name attribute change

---

ergo/distributions/conditions.py
ergo/distributions/logistic.py
tests/conftest.py
tests/test_conditions.py

Optimizes a parameterized distribution to look similar to a user-provided histogram (such as the Metaculus community distribution)

Add HistogramCondition

---

ergo/distributions/conditions.py
tests/test_conditions.py

- create IntervalCondition
- add tests of interval condition loss function

Interval condition

---

ergo/distributions/conditions.py
tests/test_conditions.py

PR is complete IMO, made as a draft because I want to compare against the `interval-condition` branch until that gets merged; can then switch this to a real PR to master

describe_fit of distributions to conditions and test

---

ergo/distributions/__init__.py
ergo/distributions/conditions.py
ergo/distributions/mixture.py
tests/test_conditions.py

and replace with IntervalCondition
still refer to "percentiles" in various places, since it still makes sense as a concept

Fully remove PercentileCondition

---

ergo/distributions/conditions.py
ergo/distributions/location_scale_family.py
ergo/distributions/mixture.py
ergo/platforms/metaculus/question/continuous.py
ergo/platforms/metaculus/question/linear.py
tests/test_conditions.py

...then denormalize the resulting mixture
1. added lots of docstrings
2. added Condition.get_denormalized, even though we don't need it. I was already mostly done adding it when I realized we didn't need it, and it helps with the tests. Still might want to remove it later, at least on the abstract base class
3. add some tests. There could definitely be more

Normalize conditions before fitting

---

ergo/distributions/conditions.py
ergo/distributions/location_scale_family.py
ergo/distributions/mixture.py
ergo/distributions/scale.py
tests/test_conditions.py
tests/test_logistic.py

2. test normalization/denormalization for logistic mixtures
3. create Scale and refactor all normalization to use it

Add normalization for logistic mixtures

---

ergo/platforms/metaculus/metaculus.py

Obviously a tiny change that shouldn't break anything, will summarily merge if tests pass

Raise for status when can't login

---

ergo/distributions/logistic_mixture.py
ergo/distributions/mixture.py
tests/test_logistic.py

Most important change is to logpdf (no longer applying softmax to params)

Various changes to logistic mixtures

---

ergo/distributions/conditions.py
tests/test_conditions.py

Add a condition for specifying what the most likely outcome will be. The loss is calculated by `(P(current_most_likely_outcome)-P(specfied_outcome)) ** 2`.

Add most likely outcome condition

---

ergo/conditions/__init__.py
ergo/conditions/mean.py
ergo/conditions/variance.py
ergo/scale.py
tests/test_conditions.py

[PDF of ipynb demonstrating use of mean and variance conditions](https://github.com/oughtinc/ergo/files/4732558/Mean.and.Variance.Condition.Testing.pdf)

Add mean and variance conditions

---

ergo/conditions/condition.py
ergo/conditions/histogram.py
ergo/conditions/mean.py
ergo/conditions/variance.py
ergo/contrib/el_paso/brachbach.py
ergo/distributions/histogram.py
ergo/distributions/logistic.py
ergo/distributions/mixture.py
ergo/distributions/optimizable.py
ergo/scale.py
notebooks/el-paso.ipynb
tests/test_conditions.py
tests/test_distributions.py
tests/test_logistic.py

scale.scale_min -> low
scale.scale_max -> high
scale.scale_range -> width

Update scale field names

---

pull_request_template.md

Linear will post the relevant issue based on the branch name

Don't require "Fixes OUG-999" in PR template

---

ergo/conditions/variance.py

one-line fix for error in variance conditions

fix improper PointDensity.variance() call

---

ergo/distributions/point_density.py

Fixes issue in https://elicit.ought.org/builder/CcVPEdUGC
Before:
After:

Fix add endpoints extrapolation

---

Makefile
ergo/contrib/el_paso/brachbach.py
setup.cfg

Note that the Linear issue explains what this is/why this is important

Incorporate linting fixes from Elicit

---

.travis.yml
poetry.lock
pyproject.toml

Support and test Python 3.7 and 3.8 on Travis

---

docs/index.rst
docs/predictit.rst
ergo/__init__.py
ergo/contrib/el_paso/brachbach.py
ergo/contrib/predictit/__init__.py
ergo/contrib/predictit/fuzzy_search.py
ergo/platforms/__init__.py
ergo/platforms/predictit.py
mypy.ini
notebooks/predictit_clean_sweep.ipynb
poetry.lock
pyproject.toml
tests/conftest.py
tests/test_predictit.py

This is https://github.com/oughtinc/ergo/pull/399 but as a PR within the original Ought fork of Ergo
This is just to run the CI, which doesn't run properly for a PR from a different fork

PredictIt API for Travis

---

ergo/platforms/metaculus/question/continuous.py

As requested in https://www.youtube.com/watch?v=aueXegwTZIM&t=0s

Sort components by descending weight before Metaculus submission

---

.gitignore

[Zack's PR](https://github.com/oughtinc/ergo/pull/425) as a branch of Ought's original fork, to run the Travis tests.
If this passes CI, we'll merge his original PR

Update gitignore to ignore PyCharm config files

---

README.md
notebooks/quickstart.ipynb
notebooks/scrubbed/quickstart.ipynb

Closes https://github.com/oughtinc/ergo/issues/424
I'm not sure what best practices are for putting Notebooks up in a PR are, so let me know if I should do anything else here.

Fix quickstart

---

ergo/platforms/metaculus/metaculus.py

Metaculus changed their API, so we need to change how we call their API

Metaculus API call fix
