.gitignore
README.md
ergo/__init__.py
ergo/data/covid19.py
ergo/metaculus.py
ergo/ppl.py
poetry.lock
pyproject.toml
tests/test_ergo.py

1. Make it easy to see what predictions you're planning to submit before you submit them via `show_submission`
2. Retrieve and display your prediction results so far via `show_prediction_results`
3. Add some tests so that you can figure out whether the API is working without firing up a Colab
Also, some housekeeping:
1. add to the README re: developing on this project
2. run autopep8 formatter on everything
Compatible with the Colab v6, as shown by: https://colab.research.google.com/drive/1xfhW9kKbr-0dkquzjWGD_OHyPHlKQMAA?hl=en#scrollTo=u5-EaP2LUfBG
The API improvements are pretty rough still, but I thought it was best to at least make a PR for them (and the housekeeping stuff) so we're all working off of the same code
Things I'd like to improve about the API improvements
1. display …

Improve Metaculus API

---

.travis.yml
README.md
ergo/data/covid19.py
ergo/logistic.py
ergo/metaculus.py
poetry.lock
pyproject.toml
tests/mocks.py
tests/test_ergo.py
tests/test_jax.py
tests/test_logistic.py
tests/test_metaculus.py

@stuhlmueller this is just running `black` over everything
IMO:
1. makes nothing worse
2. makes some things noticeably better
3. most of the changes I don't really care about
note that there are [a few](https://black.readthedocs.io/en/stable/installation_and_usage.html) things you can configure, if you really want to
I'm still in favor of switching to black and I wouldn't change any of the defaults
let me know what you think -- if you're into it then I can:
1. make sure that `flake8` is still the best choice for CI
2. change the README re: what formatter to use

Format all the files using black

---

ergo/ppl.py

Was giving me an error torch.Tensor(None) isn't valid.

Fix random_choice for case where we don't pass in probabilities

---

pyproject.toml

Readthedocs doesn't install dev dependencies

Add sphinx-autodoc-typehints to project dependencies [!pr]

---

ergo/logistic.py
ergo/ppl.py

This allows `tqdm` to detect whether it's being used in a notebook or in a console.
When `tqdm` is imported from `tqdm.autonotebook`, `tqdm.trange(...)` no longer works, so we needed to switch to `tqdm(range(...))`.
Also, `tqdm.autonotebook` doesn't come with any type hints, so we needed to add `# type: ignore` to suppress the errors for now. Maybe in the future we can add our own type hints here?
Resolves #127

Import tqdm from tqdm.autonotebook

---

ergo/metaculus.py

Simple first change. 
If a question doesn't have a name, it defaults to the question title.

Metaculus questions default names

---

ergo/metaculus.py

The Stupid Quick Fix to #125 (but does not address the more complicated requirements)
The query in get_questions_json ommits the following fields returned by the simpler query in get_question and refresh_question
simple query: `self.s.get(f"{self.api_url}/questions/{id}")`
additional fields: [author_name, prediction_histogram ,anon_prediction_count, last_read]
(Conversely the get_question_json query returns the field comment_count_snapshot, not present in the simple query (given very preliminary testing))
The present pull request just takes the union of the results but likely a more elegant solution can be found by investigating the queries and api responses more closely

now no additional question refresh necessary

---

ergo/logistic.py
ergo/metaculus.py
tests/test_logistic.py
tests/test_metaculus.py

- Would be better to use [BFGS with bounds](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html) but I ran into issues, probably caused by use of Jax arrays (and couldn't easily make it work).
- Improves fitting speed from ~13s to ~1s for [a typical case](https://github.com/oughtinc/ergo/pull/284/files#diff-3a3f306d1a1573e1a5d9916ca51c3b8aR48).

Fit logistic mixture using BFGS instead of SGD

---

ergo/logistic.py
tests/test_logistic.py

Did enough research to be convinced that the numeric ppf approximation is the way to go (some notes [here](https://docs.google.com/document/d/1K4mmR3BtvCCKGwcvjczn5KAeTz3frdT7JIgRz7uPXwE/edit#). It should work for arbitrary mixtures. If a special case becomes important we can consider hunting for analytic solutions, but that is overkill for now. 
Notes:
Currently we have a lot of logistic-specific functionality, but it might make sense to have a more abstract distribution class if we want to support many distribution types in the dist builder. E.g. mixture_cdf should be in the abstract class and delegate to the cdf function of the appropriate class (in this case Logistic). My suspicion is that you structured things as they are with jax and speed in mind, which is above my paygrade. So I …

add cdf and ppf functions for logistic mixtures

---

ergo/platforms/metaculus/question/continuous.py

does not account for values out of range.
one-line change so will merge after tests pass

Denormalize community_dist

---

ergo/platforms/metaculus/question/continuous.py

This prevented submitting predictions in Elicit for old Metaculus questions
Fairly straightforward so will summarily merge when tests pass

Deal with old Metaculus questions

---

ergo/distributions/mixture.py
tests/test_logistic.py

fixes #322
More robust extension of the min/max quartile range given the optimization function. Additionally, if there is an unexpected edgecase provide a fallback value (which for the cases tested is very close to the optimization-computed value)

made mixture ppf more robust

---

README.md

The section was renamed in f4c4de617e5ccea94de5e2cf344a4a651a78a059 but the link still points at the old name.

Fix quickstart link in README.md

---

ergo/distributions/histogram.py
tests/test_distributions.py

Bugs fixed:
- `pdf` and `cdf` not working when distribution isn't normalized.
- `pdf` and `cdf` returning wrong values when out `x` below `scale_min` or above `scale_max`.
- `ppf` sometimes erroring when `scale_max` is passed in (since the highest value in `cum_ps` is sometimes something like `scale_max`-.0001).
- Off by 1 error: Before if the `bins` was [0,0.5,1] and `ps` was [0.4,0.6] `pdf(0.25)` would have been 0.6, and `cdf(0.5)` 1. In other words the returned index in `ps`/`cum_ps` was one to the right of the correct value.

HistogramDist fixes

---

ergo/distributions/truncated_logistic_mixture.py

Similar to #327 which fixed #322, but for truncated logistic mixtures. Fixing error mentioned in [this Elicit PR](https://github.com/oughtinc/elicit/pull/170).
```
Traceback (most recent call last):
File "test_submission.py", line 81, in test_community_submission
comparisons.append(DistributionComparator(q_id, dists_to_compare, range_min, range_max))
File "test_submission.py", line 21, in __init__
self._calculate_dist_percentiles()
File "test_submission.py", line 28, in _calculate_dist_percentiles
self.dist_percentiles[i].append(round(dist.ppf(percentile), 4))
File "/home/elifland/anaconda3/envs/ought/src/ergo/ergo/distributions/truncated_logistic_mixture.py", line 49, in ppf
lambda x: self.cdf(x) - q, self.floor, self.ceiling, maxiter=1000,
File …
```

Fix truncated ppf error [!PR]

---

ergo/distributions/logistic_mixture.py
ergo/distributions/optimizable.py
ergo/distributions/truncated_logistic_mixture.py
ergo/platforms/metaculus/question/constants.py
tests/test_logistic.py

Also restrict variance to positive values.
Metaculus allows locations for a somewhat wider range than this. If this matters, we'd need to separate truncation floor/ceiling and distribution location floor/ceiling.
Needed to close https://github.com/oughtinc/elicit/issues/151

Restrict location of logistic mixture based on truncation range

---

ergo/scale.py
tests/test_scales.py

(so that, e.g., they can easily be used on the frontend), and test
Used in this Elicit PR: https://github.com/oughtinc/elicit/pull/183
I'd say that both should be merged at the same time

Export scales as dicts 

---

ergo/__init__.py
ergo/distributions/histogram.py
ergo/distributions/logistic.py
ergo/distributions/logistic_mixture.py
ergo/distributions/truncate.py
tests/test_logistic.py

This PR fixes some ppf issues with the new truncated dists and mixture of truncated dists. I tested 14 random log questions with `test_submission` and all of them computed successfully. 
Specifically this PR:
1. Updates the logistic_mixture ppf to get the starting bounds for the optimization call from the ppfs of the components. To my knowledge, there is not a principled way to get the bounds from the mixture level
2. Updated the Truncated ppf method with an analytic solution. This should be faster and less error-prone. This required re-adding the Logistic ppf method. 
3. Added tests of the new ppf methods in each of the possible bound conditions for all available scales

Improve PPF for mixture of truncated dists

---

ergo/conditions/mode.py
ergo/contrib/el_paso/brachbach.py
ergo/distributions/constants.py
ergo/distributions/histogram.py
tests/test_conditions.py

**This is associated with [this elicit PR](https://github.com/oughtinc/elicit/pull/195)**
This updates the histogram from_pairs functions to ensure that the resulting histogram tiles the entire scale. 
In the previous scheme: we had equally spaced bins in linear space. We consider the center of each bins as the 'x' coord that we pass out on pairs. For large (usually log) scales, the discrepancy from the middle of the bin to the scale edge can be visually pronounced. 
We now have the conceptual shift (more consistent with what we are given by metaculus) that we have a pdf (which is underpinned by a grid of densities that we smooth between). We can be explicit about the relationship between points if we want (it is now implicit in our smoothing and AUC function).
This update brought to …

update to work on points and tile entire scale

---

ergo/platforms/metaculus/question/continuous.py
ergo/platforms/metaculus/question/question.py

from MetaculusQuestion to ContinuosuQuestion.
for ContinuousQuestions, this indeed gives the percentiles as desired. But for BinaryQuestions, the community_prediction is a float (rather than percentiles), so this returns a float
I could have added some replacement function to BinaryQuestion, but decided not to for now because it's unclear what we'd want. Binary question prediction_timeseries have the following structure:
```
{
"t": 1592276813.6254,
"distribution": {
"avg": 0.81148,
"num": 88,
"var": 0.03514
},
"num_predictions": 124,
"community_prediction": 0.87
}
```
We might want to return the `distribution` somehow, or maybe not, but seems unclear at the moment

Move latest_community_percentiles 

---

tests/test_conditions.py

Add regression tests for two bugs
The bugs are described in the test docstrings
These tests currently fail, so they're marked with xfail
We hope that the tests will pass once we switch to PointDensity
I think it makes sense to merge these now to give us some things to work towards for PointDensity

Hist regression tests

---

ergo/platforms/metaculus/question/lineardate.py

Ergo currently uses the local timezone to turn a datetime (like the one obtained from "2020-06-30" via strptime) into a timestamp. This means it can assign different timestamps to the same Metaculus questions, depending on the timezone Ergo is operating in.
This PR changes Ergo to alway use UTC to generate the timestamp. 
This will partially fix the following Elicit issue:
Fixes OUG-209

Generate consistent UTC timestamps

---

CHANGELOG.md
ergo/__init__.py
ergo/conditions/crossentropy.py
ergo/conditions/smoothness.py
ergo/distributions/logistic_mixture.py
ergo/distributions/optimizable.py
ergo/distributions/point_density.py
ergo/platforms/metaculus/question/continuous.py
ergo/platforms/metaculus/question/linear.py
ergo/platforms/metaculus/question/log.py
ergo/scale.py
pyproject.toml

This PR has some small changes to ensure that scales always have float-valued fields. 
I've tested elicit with these updates looking at:
All combinations of scale_type and question_type
with one of each kind of bound condition (bounds not crossed with scale_type and question_type)

Point Density isnt fully precompiled

---

ergo/distributions/point_density.py
ergo/utils.py
tests/test_point_density.py

This PR has a simple fix for the situation where the density of a point/mass of a bin is 0. It adds a minuscule amount to the density prior when it is passed to a log function. 
An alternative would be to simply add this small amount to density proper, however I thought that there is end-user utility in being able to specify true 0 bins (trade-off being that there is a minuscule disconnect from the actual density and log density)

Prevent errors due to computing log of probability 0

---

ergo/platforms/metaculus/question/continuous.py
tests/test_metaculus.py

Fixes a read-only error resulting from data being an immutable `jax.np` array instead of a normal numpy array.  Also adds two tests that ensure `show_prediction()` runs without errors (although it does not test the accuracy of the graphs produced).

Fixes #408

---

ergo/platforms/metaculus/question/continuous.py
tests/conftest.py
tests/test_metaculus.py

This branch fixes a problem where ergo would successfully fit a logistic mixture to a distribution but then skew it subtly.  Specifically, when called without passing a scale, the logistic mixture fitting function will use an appropriate scale based on the min and max of the data.  We were then fitting to the normalized data, but the resulting distribution had a scale that was not exactly `[0,1]`. The function that prepares the data for Metaculus submission assumes that it is given a normalized distribution, causing the submitted distribution to be shifted slightly.
This PR also includes a new test for fitting a fairly smooth distribution that the current master code fails.  Unfortunately, the existing fitting tests are still failing for other reasons.  Specifically, ergo seems to …

Fix scaling for logistic fit

---

ergo/platforms/metaculus/metaculus.py

Closes #363. There wasn't a great way to test this without exposing too much from the Metaculus class, thought if you disallow redirects, as I have done, but don't add the `/`, the tests will fail.

Add '/' to Metacalculus questions url to remove redirect

---

.travis.yml
Makefile
ergo/platforms/metaculus/metaculus.py
tests/conftest.py
tests/test_metaculus.py

1. only run them for one of the Python versions, not all 3
1. otherwise we hit the Metaculus API too much and it errors
2. in Travis settings, disable extra test runs (again, to avoid hitting Metaculus too much)
3. include the test username and password in source code
1. So that anyone can run these tests, including Travis when it's running on a fork other than Ought's
4. skip the tests that require API access if you don't have an API key
1. So that these tests don't fail for users without an API key, including Travis when it's running on a fork other than Ought's
5. delete the Metaculus doctest -- it was failing on my fork and I couldn't fix it really easily, so just get rid of it

Avoid Metaculus tests causing Travis build to fail
